on:
  schedule:
      - cron: "5 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script.
      run: |
        python main.py
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        WANIKANI_ACCESS_TOKEN: ${{ secrets.WANIKANI_ACCESS_TOKEN }}